werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:36:52] "[33mGET / HTTP/1.1[0m" 404 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:09] "[32mGET /pashto HTTP/1.1[0m" 308 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:09] "[37mGET /pashto/ HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:09] "[37mGET /pashto/pashto/static/scripts/pashto.js HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:09] "[37mGET /pashto/pashto/static/style/definition.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:10] "[37mGET /pashto/pashto/static/style/main.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:37:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[32mGET /pashto HTTP/1.1[0m" 308 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[37mGET /pashto/ HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[37mGET /pashto/pashto/static/scripts/pashto.js HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[37mGET /pashto/pashto/static/style/definition.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[37mGET /pashto/pashto/static/style/main.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:26] "[37mGET /pashto/ HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:28] "[37mGET /pashto/pashto/static/style/search.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:47] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:47] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:47] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:47] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:48] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:48] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:37:48] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:14] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:14] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:14] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:14] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:15] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:16] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:17] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:27] "[37mPOST /pashto/meaning HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:37] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:38] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:38] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:38] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:38] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:45] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:45] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:50] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:50] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:50] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:38:50] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:02] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:02] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:03] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:03] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:10] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:10] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:23] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:23] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:24] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:24] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:25] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:25] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:41] "[37mPOST /pashto/meaning HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:56] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:56] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:56] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:56] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:56] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:39:57] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
app - ERROR - Exception on /pashto/update_suggestions [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 58, in my_form_post
    response += [dict_trie.get_data(i) for i in get_close_matches(query)]
  File "/Users/emadsiddiq/Projects/personal_website/pashto/pashto.py", line 29, in get_close_matches
    matches_pashto = match_strings(df['pashto'], search_terms, min_similarity = 0.3)
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 33, in match_strings
    string_grouper = StringGrouper(master, duplicates=duplicates, **kwargs).fit()
  File "/Users/emadsiddiq/Projects/personal_website/pashto/string_grouper.py", line 59, in __init__
    if not StringGrouper._is_series_of_strings(master) or \
AttributeError: type object 'StringGrouper' has no attribute '_is_series_of_strings'
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.234 - - [16/Aug/2020 20:40:58] "[35m[1mPOST /pashto/update_suggestions HTTP/1.1[0m" 500 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:47:05] "[37mGET /pashto/pashto/static/style/search.css HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:47:06] "[37mPOST /pashto/update_suggestions HTTP/1.1[0m" 200 -
werkzeug - INFO - 10.0.0.163 - - [16/Aug/2020 20:47:08] "[37mPOST /pashto/meaning HTTP/1.1[0m" 200 -
